name: Firs Action - Simple

on:
  workflow_dispatch:

jobs:
  hello-world:
  runs-on: ubuntu-latest

  steps:
    - name: Hello World
      run: echo "Hello, world!"
    - name: Hello World 2
      run: echo "Hello, world! 2"