name: Firs Action - Simple

on:
  workflow_dispatch:
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
    - name: Fist Step
      run: echo "Hello World"
  
  bye-world:
    runs-on: ubunto-latest
    needs: hello-world
    steps:
    - name: bye World
      run: echo "Hello, world!"

on:
  workflow_dispatch:
    inputs:
      debug_mode:
        type: boolean
        description: Debug
        default: false
        required: false
      sample_value:
        type: string
        description: Cualquier valor
        default: ""
        required: false   